name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install SDL2
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --lib --bins --tests --examples
      - name: Run clippy
        run: cargo clippy --all-targets --all-features
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - name: Test WASM frontend
        run: wasm-pack test --headless --chrome --features wasm
      - name: Test web frontend
        run: npm ci && npm test
